name: WebSiteTest
on:
  push:
    branches: 
    - '*'
jobs:    
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set selected color
      run: echo '${{ secrets.AZURE_CREDENTIALS }}'      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']"