name: WebSiteTest
on:
  push:
    branches: 
    - '*'
jobs:    
    build:      
      name: Build 
      runs-on: ubuntu-latest
      steps:        
        - uses: actions/checkout@v2                           
        