name: WebSiteTest
on:
  push:
    branches: 
    - '*'
env: # Or as an environment variable
  credentials: ${{ secrets.AZURE_CREDENTIALS }}
jobs:    
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set selected color
      run: echo $credentials      
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - run: |
        az webapp list --query "[?state=='Running']"