name: WebSiteTest
on:
  push:
    branches: 
    - '*'
env: # Or as an environment variable
  credentials: ${{ secrets.AZURE_CREDENTIALS }}
jobs:    
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        allow-no-subscriptions: true
    - uses: actions/checkout@v2 
    - name: Build
      shell: pwsh
      run: |
        .\build.ps1
    - run: |
        az webapp list --query "[?state=='Running']"